### PR TITLE
Adds initial support for win32

### PR DESCRIPTION
**Pull request by stefanbc**
Using the `net statistics workstation` command and then extracting the date using regex. This is just an initial version for win32 support. The regex string could and should be improved.

### CODE REVIEW

**Comment by stefanbc** [comment]
Also I'm planning on doing a bit of cleaning inside the repo and give it a bit of structure.

**Comment by stefanbc** [comment]
Made some improvements including the ones I mentioned in the previous comment.

**Comment by oroce** [comment]
@stefanbc please move back files to the root directory, I want as flat structure as possible.
Also the master has appveyor build so we can run the tests on windows as well.

**Comment by stefanbc** [comment]
@oroce should be all good now. 👍

**Comment by oroce** [comment]
@stefanbc i slightly changed the style of your pr (4ea88db), somehow I forgot to [`prefer-const`](http://eslint.org/docs/rules/prefer-const) to the eslint config.

Thanks for your PR!

**Comment by oroce** [comment]
published as `v2.0.0`

**Comment by stefanbc** [comment]
No worries. Awesome. My pleasure. 👍

**Pull request merged**
